prometheusRules:
  - alert: HTTPStatusCodesShowServiceUnhealthy
    expr: sum(increase(traefik_backend_requests_total{backend="selected-tests.server-tig.staging.corp.mongodb.com/", code!="200", code!="201", code!="204"}[1h])) > 1
    for: 5m
    labels:
      severity: warning
      email_to: jeff.zambory@mongodb.com
    annotations:
      description: "High number of bad responses coming from selected-tests service"
      summary: "Selected test service giving high number of bad responses over the last hour (current number: {{ $value }}). More information can be seen here: https://grafana.corp.mongodb.com/d/zenZa6oWk/selected-tests-service?orgId=4"